config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :authors
  resources :genres
  resources :publishers
  resources :notes
  resources :customers
  resources :suppliers
  resources :supplier_orders
  resources :orders
  resources :detail_orders
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end


  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "notes#index"

  resources :roles
end

app/models/author.rb
class Author < ApplicationRecord
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  belongs_to :genre
  belongs_to :publisher
end

app/models/customer.rb
class Customer < ApplicationRecord
    validates_uniqueness_of :email, :phone
end

app/models/detail_order.rb
class DetailOrder < ApplicationRecord
  belongs_to :order
  belongs_to :note
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :notes

    validates_uniqueness_of :name
    validates_presence_of :name
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :author
  belongs_to :genre
  belongs_to :publisher
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :detaik_order
  
  validates_presence_of :price
  validates_numericality_of :price

end

app/models/publisher.rb
class Publisher < ApplicationRecord
    has_many :publisher_order

    validates_presence_of :name
    validates_uniqueness_of :name
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/status.rb
class Status < ApplicationRecord
end

app/models/supplier.rb
class Supplier < ApplicationRecord
    has_many :supplier_order
end

app/models/supplier_order.rb
class SupplierOrder < ApplicationRecord
  belongs_to :supplier
  belongs_to :note
end

app/models/user.rb
class User < ApplicationRecord
has_person_name

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i[ show edit update destroy ]

  # GET /notes or /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1 or /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes or /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to note_url(@note), notice: "Note was successfully created." }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to note_url(@note), notice: "Note was successfully updated." }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1 or /notes/1.json
  def destroy
    @note.destroy

    respond_to do |format|
      format.html { redirect_to notes_url, notice: "Note was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:title, :author_id, :genre_id, :publisher_id, :isbn, :publish_year, :price, :stock_quantity)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/notes/_form.html.erb
<%= form_with(model: note) do |form| %>
<% if note.errors.any? %>
<div id="error_explanation" class="bg-red-50 p-6 rounded text-red-800">
  <h2 class="text-lg font-semibold mb-3"><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

  <ul class="list-disc leading-relaxed">
    <% note.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

  <div class="mb-6">
        <%= form.label :title, class: label_class %>
          <%= form.text_field :title, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :author_id, class: label_class %>
          <%= form.select :author_id, options_from_collection_for_select( Author.all, 'id', 'name', selected = note.author_id), class: label_class %>
      </div>
  <div class="mb-6">
        <%= form.label :genre_id, class: label_class %>
          <%= form.select :genre_id, options_from_collection_for_select( Genre.all, 'id', 'name', selected = note.genre_id), class: label_class %>
      </div>
  <div class="mb-6">
        <%= form.label :publisher_id, class: label_class %>
          <%= form.select :pulisher_id, options_from_collection_for_select( Publisher.all, 'id', 'name', selected = note.publisher_id), class: label_class %>
      </div>
  <div class="mb-6">
        <%= form.label :isbn, class: label_class %>
          <%= form.text_field :isbn, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :publish_year, class: label_class %>
          <%= form.number_field :publish_year, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :price, class: label_class %>
          <%= form.text_field :price, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :stock_quantity, class: label_class %>
          <%= form.number_field :stock_quantity, class: input_class %>
      </div>

<%= form.submit class: button_class(theme: 'primary') %>

<% if note.persisted? %>
<%= link_to "Cancel", note, class: "text-neutral-700 underline inline-block ml-3" %>
<% else %>
<%= link_to "Cancel", notes_path, class:  "text-neutral-700 underline inline-block ml-3" %>
<% end %>
<% end %>

app/views/notes/_note.html.erb
<div id="<%= dom_id note %>">
  <p>
    <strong>Title:</strong>
    <%= note.title %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= note.author_id %>
  </p>

  <p>
    <strong>Genre:</strong>
    <%= note.genre_id %>
  </p>

  <p>
    <strong>Publisher:</strong>
    <%= note.publisher_id %>
  </p>

  <p>
    <strong>Isbn:</strong>
    <%= note.isbn %>
  </p>

  <p>
    <strong>Publish year:</strong>
    <%= note.publish_year %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= note.price %>
  </p>

  <p>
    <strong>Stock quantity:</strong>
    <%= note.stock_quantity %>
  </p>

</div>

app/views/notes/edit.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between mb-6 flex-wrap">
    <h1 class="font-bold text-3xl mb-6">Edit note</h1>
    <% if @note.persisted? %>
    <%= button_to 'Destroy', @note, method: :delete, class: "text-red-700 underline", data: { turbo_confirm: 'Are you sure?' } %>
    <% end %>
  </div>

  <%= render 'form', note: @note %>
</div>

app/views/notes/index.html.erb
<div class="container mx-auto px-4">
  <div class="flex items-center justify-between flex-wrap mb-6">
    <h1 class="text-3xl font-bold">Books</h1>

    <%= link_to new_note_path, class: button_class(theme: "primary") do %>
    Add New Note
    <% end %>
  </div>

  <table class="table-auto border-collapse border-slate-400 w-full">
    <thead class="bg-slate-50 dark:bg-slate-700">
      <tr>
        
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Title</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Author</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Genre</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Publisher</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Isbn</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Publish year</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Price</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Stock quantity</th>
                
          <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left"></th>
        
      </tr>
    </thead>

    <tbody>
      <% @notes.each do |note| %>
      <%= content_tag :tr, id: dom_id(note), class: dom_class(note) do %>
      

              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= note.title %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= note.author.name %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= note.genre.name %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= note.publisher.name %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= note.isbn %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= note.publish_year %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= note.price %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= note.stock_quantity %></td>
      
      
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= link_to 'Show', note %></td>
      
      <% end %>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/notes/new.html.erb
<div class="max-w-3xl mx-auto px-4">
  <h1 class="font-bold text-3xl mb-6">New note</h1>

  <%= render 'form', note: @note %>
</div>

app/views/notes/show.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between">
    <h1 class="flex-1 font-bold text-3xl">Note</h1>

    <div class="flex-wrap lg:flex items-center lg:space-x-3">
      <%= link_to notes_path, class: button_class(theme: "transparent") do %>
      All Notes
      <% end %>
      <%= link_to edit_note_path(@note), class: button_class(theme:"primary") do %>
      Edit
      <% end %>
    </div>
  </div>

  <ul class="text-slate-700">
      <li>
        <p class="font-semibold">Title:</p>
        <p><%= @note.title %></p>
      </li>
      <li>
        <p class="font-semibold">Author:</p>
        <p><%= @note.author %></p>
      </li>
      <li>
        <p class="font-semibold">Genre:</p>
        <p><%= @note.genre %></p>
      </li>
      <li>
        <p class="font-semibold">Publisher:</p>
        <p><%= @note.publisher %></p>
      </li>
      <li>
        <p class="font-semibold">Isbn:</p>
        <p><%= @note.isbn %></p>
      </li>
      <li>
        <p class="font-semibold">Publish year:</p>
        <p><%= @note.publish_year %></p>
      </li>
      <li>
        <p class="font-semibold">Price:</p>
        <p><%= @note.price %></p>
      </li>
      <li>
        <p class="font-semibold">Stock quantity:</p>
        <p><%= @note.stock_quantity %></p>
      </li>
  </ul>
</div>