config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :authors
  resources :genres
  resources :publishers
  resources :notes
  resources :customers
  resources :suppliers
  resources :supplier_orders
  resources :orders
  resources :detail_orders
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end


  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "notes#index"

  resources :roles
end

app/models/author.rb
class Author < ApplicationRecord
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  belongs_to :genre
  belongs_to :publisher
end

app/models/customer.rb
class Customer < ApplicationRecord
    validates_uniqueness_of :email, :phone
end

app/models/detail_order.rb
class DetailOrder < ApplicationRecord
  belongs_to :order
  belongs_to :note
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :notes

    validates_uniqueness_of :name
    validates_presence_of :name
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :author
  belongs_to :genre
  belongs_to :publisher
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :detaik_order
  
  validates_presence_of :price
  validates_numericality_of :price

end

app/models/publisher.rb
class Publisher < ApplicationRecord
    has_many :publisher_order

    validates_presence_of :name
    validates_uniqueness_of :name
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/status.rb
class Status < ApplicationRecord
end

app/models/supplier.rb
class Supplier < ApplicationRecord
    has_many :supplier_order
end

app/models/supplier_order.rb
class SupplierOrder < ApplicationRecord
  belongs_to :supplier
  belongs_to :note
end

app/models/user.rb
class User < ApplicationRecord
has_person_name

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/detail_orders_controller.rb
class DetailOrdersController < ApplicationController
  before_action :set_detail_order, only: %i[ show edit update destroy ]

  # GET /detail_orders or /detail_orders.json
  def index
    @detail_orders = DetailOrder.all
  end

  # GET /detail_orders/1 or /detail_orders/1.json
  def show
  end

  # GET /detail_orders/new
  def new
    @detail_order = DetailOrder.new
  end

  # GET /detail_orders/1/edit
  def edit
  end

  # POST /detail_orders or /detail_orders.json
  def create
    @detail_order = DetailOrder.new(detail_order_params)

    respond_to do |format|
      if @detail_order.save
        format.html { redirect_to detail_order_url(@detail_order), notice: "Detail order was successfully created." }
        format.json { render :show, status: :created, location: @detail_order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @detail_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /detail_orders/1 or /detail_orders/1.json
  def update
    respond_to do |format|
      if @detail_order.update(detail_order_params)
        format.html { redirect_to detail_order_url(@detail_order), notice: "Detail order was successfully updated." }
        format.json { render :show, status: :ok, location: @detail_order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @detail_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /detail_orders/1 or /detail_orders/1.json
  def destroy
    @detail_order.destroy

    respond_to do |format|
      format.html { redirect_to detail_orders_url, notice: "Detail order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_detail_order
      @detail_order = DetailOrder.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def detail_order_params
      params.require(:detail_order).permit(:order_id, :note_id, :quantity, :total_price, :payment_method)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/detail_orders_helper.rb
module DetailOrdersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/detail_orders/_detail_order.html.erb
<div id="<%= dom_id detail_order %>">
  <p>
    <strong>Order:</strong>
    <%= detail_order.order_id %>
  </p>

  <p>
    <strong>Note:</strong>
    <%= detail_order.note_id %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= detail_order.quantity %>
  </p>

  <p>
    <strong>Total price:</strong>
    <%= detail_order.total_price %>
  </p>

  <p>
    <strong>Payment method:</strong>
    <%= detail_order.payment_method %>
  </p>

</div>

app/views/detail_orders/_form.html.erb
<%= form_with(model: detail_order) do |form| %>
<% if detail_order.errors.any? %>
<div id="error_explanation" class="bg-red-50 p-6 rounded text-red-800">
  <h2 class="text-lg font-semibold mb-3"><%= pluralize(detail_order.errors.count, "error") %> prohibited this detail_order from being saved:</h2>

  <ul class="list-disc leading-relaxed">
    <% detail_order.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

  <div class="mb-6">
        <%= form.label :order_id, class: label_class %>
          <%= form.select :order_id, options_from_collection_for_select( Order.all, 'id', 'name', selected = detail_order.order_id), class: label_class %>
      </div>
  <div class="mb-6">
        <%= form.label :note_id, class: label_class %>
          <%= form.select :note_id, options_from_collection_for_select( Note.all, 'id', 'name', selected = detail_order.note_id), class: label_class %>
      </div>
  <div class="mb-6">
        <%= form.label :quantity, class: label_class %>
          <%= form.number_field :quantity, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :total_price, class: label_class %>
          <%= form.text_field :total_price, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :payment_method, class: label_class %>
          <%= form.text_field :payment_method, class: input_class %>
      </div>

<%= form.submit class: button_class(theme: 'primary') %>

<% if detail_order.persisted? %>
<%= link_to "Cancel", detail_order, class: "text-neutral-700 underline inline-block ml-3" %>
<% else %>
<%= link_to "Cancel", detail_orders_path, class:  "text-neutral-700 underline inline-block ml-3" %>
<% end %>
<% end %>

app/views/detail_orders/edit.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between mb-6 flex-wrap">
    <h1 class="font-bold text-3xl mb-6">Edit detail_order</h1>
    <% if @detail_order.persisted? %>
    <%= button_to 'Destroy', @detail_order, method: :delete, class: "text-red-700 underline", data: { turbo_confirm: 'Are you sure?' } %>
    <% end %>
  </div>

  <%= render 'form', detail_order: @detail_order %>
</div>

app/views/detail_orders/index.html.erb
<div class="container mx-auto px-4">
  <div class="flex items-center justify-between flex-wrap mb-6">
    <h1 class="text-3xl font-bold">Detail Orders</h1>

    <%= link_to new_detail_order_path, class: button_class(theme: "primary") do %>
    Add New Detail order
    <% end %>
  </div>

  <table class="table-auto border-collapse border-slate-400 w-full">
    <thead class="bg-slate-50 dark:bg-slate-700">
      <tr>
        
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Order</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Book</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Quantity</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Total price</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Payment method</th>
                
          <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left"></th>
        
      </tr>
    </thead>

    <tbody>
      <% @detail_orders.each do |detail_order| %>
      <%= content_tag :tr, id: dom_id(detail_order), class: dom_class(detail_order) do %>
      

              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= detail_order.order %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= detail_order.note %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= detail_order.quantity %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= detail_order.total_price %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= detail_order.payment_method %></td>
      
      
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= link_to 'Show', detail_order %></td>
      
      <% end %>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/detail_orders/new.html.erb
<div class="max-w-3xl mx-auto px-4">
  <h1 class="font-bold text-3xl mb-6">New detail_order</h1>

  <%= render 'form', detail_order: @detail_order %>
</div>

app/views/detail_orders/show.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between">
    <h1 class="flex-1 font-bold text-3xl">Detail_order</h1>

    <div class="flex-wrap lg:flex items-center lg:space-x-3">
      <%= link_to detail_orders_path, class: button_class(theme: "transparent") do %>
      All Detail_orders
      <% end %>
      <%= link_to edit_detail_order_path(@detail_order), class: button_class(theme:"primary") do %>
      Edit
      <% end %>
    </div>
  </div>

  <ul class="text-slate-700">
      <li>
        <p class="font-semibold">Order:</p>
        <p><%= @detail_order.order %></p>
      </li>
      <li>
        <p class="font-semibold">Book:</p>
        <p><%= @detail_order.note %></p>
      </li>
      <li>
        <p class="font-semibold">Quantity:</p>
        <p><%= @detail_order.quantity %></p>
      </li>
      <li>
        <p class="font-semibold">Total price:</p>
        <p><%= @detail_order.total_price %></p>
      </li>
      <li>
        <p class="font-semibold">Payment method:</p>
        <p><%= @detail_order.payment_method %></p>
      </li>
  </ul>
</div>