config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :authors
  resources :genres
  resources :publishers
  resources :notes
  resources :customers
  resources :suppliers
  resources :supplier_orders
  resources :orders
  resources :detail_orders
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end


  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "notes#index"

  resources :roles
end

app/models/author.rb
class Author < ApplicationRecord
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  belongs_to :genre
  belongs_to :publisher
end

app/models/customer.rb
class Customer < ApplicationRecord
    validates_uniqueness_of :email, :phone
end

app/models/detail_order.rb
class DetailOrder < ApplicationRecord
  belongs_to :order
  belongs_to :note
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :notes

    validates_uniqueness_of :name
    validates_presence_of :name
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :author
  belongs_to :genre
  belongs_to :publisher
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :detaik_order
  
  validates_presence_of :price
  validates_numericality_of :price

end

app/models/publisher.rb
class Publisher < ApplicationRecord
    has_many :publisher_order

    validates_presence_of :name
    validates_uniqueness_of :name
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/status.rb
class Status < ApplicationRecord
end

app/models/supplier.rb
class Supplier < ApplicationRecord
    has_many :supplier_order
end

app/models/supplier_order.rb
class SupplierOrder < ApplicationRecord
  belongs_to :supplier
  belongs_to :note
end

app/models/user.rb
class User < ApplicationRecord
has_person_name

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: %i[ show edit update destroy ]

  # GET /authors or /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1 or /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors or /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to author_url(@author), notice: "Author was successfully created." }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1 or /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to author_url(@author), notice: "Author was successfully updated." }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1 or /authors/1.json
  def destroy
    @author.destroy

    respond_to do |format|
      format.html { redirect_to authors_url, notice: "Author was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def author_params
      params.require(:author).permit(:name, :biography)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/authors/_author.html.erb
<div id="<%= dom_id author %>">
  <p>
    <strong>Name:</strong>
    <%= author.name %>
  </p>

  <p>
    <strong>Biography:</strong>
    <%= author.biography %>
  </p>

</div>

app/views/authors/_form.html.erb
<%= form_with(model: author) do |form| %>
<% if author.errors.any? %>
<div id="error_explanation" class="bg-red-50 p-6 rounded text-red-800">
  <h2 class="text-lg font-semibold mb-3"><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

  <ul class="list-disc leading-relaxed">
    <% author.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

  <div class="mb-6">
        <%= form.label :name, class: label_class %>
          <%= form.text_field :name, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :biography, class: label_class %>
          <%= form.text_field :biography, class: input_class %>
      </div>

<%= form.submit class: button_class(theme: 'primary') %>

<% if author.persisted? %>
<%= link_to "Cancel", author, class: "text-neutral-700 underline inline-block ml-3" %>
<% else %>
<%= link_to "Cancel", authors_path, class:  "text-neutral-700 underline inline-block ml-3" %>
<% end %>
<% end %>

app/views/authors/edit.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between mb-6 flex-wrap">
    <h1 class="font-bold text-3xl mb-6">Edit author</h1>
    <% if @author.persisted? %>
    <%= button_to 'Destroy', @author, method: :delete, class: "text-red-700 underline", data: { turbo_confirm: 'Are you sure?' } %>
    <% end %>
  </div>

  <%= render 'form', author: @author %>
</div>

app/views/authors/index.html.erb
<div class="container mx-auto px-4">
  <div class="flex items-center justify-between flex-wrap mb-6">
    <h1 class="text-3xl font-bold">Authors</h1>

    <%= link_to new_author_path, class: button_class(theme: "primary") do %>
    Add New Author
    <% end %>
  </div>

  <table class="table-auto border-collapse border-slate-400 w-full">
    <thead class="bg-slate-50 dark:bg-slate-700">
      <tr>
        
          <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Name</th>
        
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Biography</th>
                
      </tr>
    </thead>

    <tbody>
      <% @authors.each do |author| %>
      <%= content_tag :tr, id: dom_id(author), class: dom_class(author) do %>
      
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= link_to author.name, author %></td>
      

              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= author.biography %></td>
      
      
      <% end %>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/authors/new.html.erb
<div class="max-w-3xl mx-auto px-4">
  <h1 class="font-bold text-3xl mb-6">New author</h1>

  <%= render 'form', author: @author %>
</div>

app/views/authors/show.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between">
    <h1 class="flex-1 font-bold text-3xl">Author</h1>

    <div class="flex-wrap lg:flex items-center lg:space-x-3">
      <%= link_to authors_path, class: button_class(theme: "transparent") do %>
      All Authors
      <% end %>
      <%= link_to edit_author_path(@author), class: button_class(theme:"primary") do %>
      Edit
      <% end %>
    </div>
  </div>

  <ul class="text-slate-700">
      <li>
        <p class="font-semibold">Name:</p>
        <p><%= @author.name %></p>
      </li>
      <li>
        <p class="font-semibold">Biography:</p>
        <p><%= @author.biography %></p>
      </li>
  </ul>
</div>