config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :authors
  resources :genres
  resources :publishers
  resources :notes
  resources :customers
  resources :suppliers
  resources :supplier_orders
  resources :orders
  resources :detail_orders
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end


  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "notes#index"

  resources :roles
end

app/models/author.rb
class Author < ApplicationRecord
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  belongs_to :genre
  belongs_to :publisher
end

app/models/customer.rb
class Customer < ApplicationRecord
    validates_uniqueness_of :email, :phone
end

app/models/detail_order.rb
class DetailOrder < ApplicationRecord
  belongs_to :order
  belongs_to :note
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :notes

    validates_uniqueness_of :name
    validates_presence_of :name
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :author
  belongs_to :genre
  belongs_to :publisher
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :detaik_order
  
  validates_presence_of :price
  validates_numericality_of :price

end

app/models/publisher.rb
class Publisher < ApplicationRecord
    has_many :publisher_order

    validates_presence_of :name
    validates_uniqueness_of :name
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/status.rb
class Status < ApplicationRecord
end

app/models/supplier.rb
class Supplier < ApplicationRecord
    has_many :supplier_order
end

app/models/supplier_order.rb
class SupplierOrder < ApplicationRecord
  belongs_to :supplier
  belongs_to :note
end

app/models/user.rb
class User < ApplicationRecord
has_person_name

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/supplier_orders_controller.rb
class SupplierOrdersController < ApplicationController
  before_action :set_supplier_order, only: %i[ show edit update destroy ]

  # GET /supplier_orders or /supplier_orders.json
  def index
    @supplier_orders = SupplierOrder.all
  end

  # GET /supplier_orders/1 or /supplier_orders/1.json
  def show
  end

  # GET /supplier_orders/new
  def new
    @supplier_order = SupplierOrder.new
  end

  # GET /supplier_orders/1/edit
  def edit
  end

  # POST /supplier_orders or /supplier_orders.json
  def create
    @supplier_order = SupplierOrder.new(supplier_order_params)

    respond_to do |format|
      if @supplier_order.save
        format.html { redirect_to supplier_order_url(@supplier_order), notice: "Supplier order was successfully created." }
        format.json { render :show, status: :created, location: @supplier_order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @supplier_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /supplier_orders/1 or /supplier_orders/1.json
  def update
    respond_to do |format|
      if @supplier_order.update(supplier_order_params)
        format.html { redirect_to supplier_order_url(@supplier_order), notice: "Supplier order was successfully updated." }
        format.json { render :show, status: :ok, location: @supplier_order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @supplier_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /supplier_orders/1 or /supplier_orders/1.json
  def destroy
    @supplier_order.destroy

    respond_to do |format|
      format.html { redirect_to supplier_orders_url, notice: "Supplier order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supplier_order
      @supplier_order = SupplierOrder.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def supplier_order_params
      params.require(:supplier_order).permit(:supplier_id, :note_id, :quantity, :cost)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/supplier_orders_helper.rb
module SupplierOrdersHelper
end

app/views/supplier_orders/_form.html.erb
<%= form_with(model: supplier_order) do |form| %>
<% if supplier_order.errors.any? %>
<div id="error_explanation" class="bg-red-50 p-6 rounded text-red-800">
  <h2 class="text-lg font-semibold mb-3"><%= pluralize(supplier_order.errors.count, "error") %> prohibited this supplier_order from being saved:</h2>

  <ul class="list-disc leading-relaxed">
    <% supplier_order.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

  <div class="mb-6">
        <%= form.label :supplier_id, class: label_class %>
          <%= form.select :supplier_id, options_from_collection_for_select( Supllier.all, 'id', 'name', selected = supplier_order.supplier_id), class: label_class %>
      </div>
  <div class="mb-6">
        <%= form.label :note_id, class: label_class %>
        <%= form.select :note_id, options_from_collection_for_select( Note.all, 'id', 'name', selected = supplier_order.note_id), class: label_class %>
      </div>
  <div class="mb-6">
        <%= form.label :quantity, class: label_class %>
          <%= form.number_field :quantity, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :cost, class: label_class %>
          <%= form.text_field :cost, class: input_class %>
      </div>

<%= form.submit class: button_class(theme: 'primary') %>

<% if supplier_order.persisted? %>
<%= link_to "Cancel", supplier_order, class: "text-neutral-700 underline inline-block ml-3" %>
<% else %>
<%= link_to "Cancel", supplier_orders_path, class:  "text-neutral-700 underline inline-block ml-3" %>
<% end %>
<% end %>

app/views/supplier_orders/_supplier_order.html.erb
<div id="<%= dom_id supplier_order %>">
  <p>
    <strong>Supplier:</strong>
    <%= supplier_order.supplier_id %>
  </p>

  <p>
    <strong>Note:</strong>
    <%= supplier_order.note_id %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= supplier_order.quantity %>
  </p>

  <p>
    <strong>Cost:</strong>
    <%= supplier_order.cost %>
  </p>

</div>

app/views/supplier_orders/edit.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between mb-6 flex-wrap">
    <h1 class="font-bold text-3xl mb-6">Edit supplier_order</h1>
    <% if @supplier_order.persisted? %>
    <%= button_to 'Destroy', @supplier_order, method: :delete, class: "text-red-700 underline", data: { turbo_confirm: 'Are you sure?' } %>
    <% end %>
  </div>

  <%= render 'form', supplier_order: @supplier_order %>
</div>

app/views/supplier_orders/index.html.erb
<div class="container mx-auto px-4">
  <div class="flex items-center justify-between flex-wrap mb-6">
    <h1 class="text-3xl font-bold">Supplier Orders</h1>

    <%= link_to new_supplier_order_path, class: button_class(theme: "primary") do %>
    Add New Supplier order
    <% end %>
  </div>

  <table class="table-auto border-collapse border-slate-400 w-full">
    <thead class="bg-slate-50 dark:bg-slate-700">
      <tr>
        
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Supplier</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Book</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Quantity</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Cost</th>
                
          <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left"></th>
        
      </tr>
    </thead>

    <tbody>
      <% @supplier_orders.each do |supplier_order| %>
      <%= content_tag :tr, id: dom_id(supplier_order), class: dom_class(supplier_order) do %>
      

              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= supplier_order.supplier.name %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= supplier_order.note %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= supplier_order.quantity %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= supplier_order.cost %></td>
      
      
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= link_to 'Show', supplier_order %></td>
      
      <% end %>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/supplier_orders/new.html.erb
<div class="max-w-3xl mx-auto px-4">
  <h1 class="font-bold text-3xl mb-6">New supplier_order</h1>

  <%= render 'form', supplier_order: @supplier_order %>
</div>

app/views/supplier_orders/show.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between">
    <h1 class="flex-1 font-bold text-3xl">Supplier_order</h1>

    <div class="flex-wrap lg:flex items-center lg:space-x-3">
      <%= link_to supplier_orders_path, class: button_class(theme: "transparent") do %>
      All Supplier_orders
      <% end %>
      <%= link_to edit_supplier_order_path(@supplier_order), class: button_class(theme:"primary") do %>
      Edit
      <% end %>
    </div>
  </div>

  <ul class="text-slate-700">
      <li>
        <p class="font-semibold">Supplier:</p>
        <p><%= @supplier_order.supplier %></p>
      </li>
      <li>
        <p class="font-semibold">Note:</p>
        <p><%= @supplier_order.note %></p>
      </li>
      <li>
        <p class="font-semibold">Quantity:</p>
        <p><%= @supplier_order.quantity %></p>
      </li>
      <li>
        <p class="font-semibold">Cost:</p>
        <p><%= @supplier_order.cost %></p>
      </li>
  </ul>
</div>